### ISSUE TITLE
Teensy 3.2

### ISSUE THREAD

**Issue by Fluxanode** [WMXZ-EU/MTP_t4#8]
I have tried really hard and cannot get this to work on a teensy 3.2.  I have the latest version of Teensyduino, done all of the the mods as per instructions.  It compiles the source files with no issues but is does not work like the original yoonghm/MTP code.  It is not showing up in Windows explorer as a drive.  Is there some place to set the CS pin? I am using the SPI and change made the changes for that.  Can you help me out with some ideas?

**Comment by WMXZ-EU** [comment]
If you use mtp_test example, you have to modify the SPI settings SD_MOSI etc, sd_str[] and cs[] to reflect your configuration.
All this is in function store_configure(), which is called from setup

**Comment by Fluxanode** [comment]
I don't see store_configure() in setup.  Maybe usb_mtp_configure()?  What file is the function in so i can edit?
My setup function in mpt_test.

void setup()
{ 
  while(!Serial && millis()<3000); 
  usb_mtp_configure();
  if(!Storage_init()) {Serial.println("No storage"); while(1);};

  Serial.println("MTP test");

#if USE_SDIO==1
  pinMode(13,OUTPUT);
#endif

**Comment by Fluxanode** [comment]
Ok I just updated to the latest.  So for spi use_sd is 1? Where is the CS pin set up? maybe here 
const int cs[] = {BUILTIN_SDCARD,38}; // edit to reflect your configuration

Compiled the  MTP_test for T3.2 and getting these errors?

D:\ChuckW\Arduino\mtp-test\mtp-test\mtp-test.ino:30:21: error: 'BUILTIN_SDCARD' was not declared in this scope
   const int cs[] = {BUILTIN_SDCARD,10}; // edit to reflect your configuration
                     ^
D:\ChuckW\Arduino\mtp-test\mtp-test\mtp-test.ino: In function 'void storage_configure()':
D:\ChuckW\Arduino\mtp-test\mtp-test\mtp-test.ino:60:20: error: 'BUILTIN_SDCARD' was not declared in this scope
     { if(cs[ii] == BUILTIN_SDCARD)
                    ^
D:\ChuckW\Arduino\mtp-test\mtp-test\mtp-test.ino: In function 'void setup()':
D:\ChuckW\Arduino\mtp-test\mtp-test\mtp-test.ino:105:21: error: 'usb_mtp_configure' was not declared in this scope
   usb_mtp_configure();
                     ^

**Comment by WMXZ-EU** [comment]
T3.2 has no BUILTIN_SDCARD , which is a 'pseudo CS for T3.6
updated example should compile also on T3.2

**Comment by Fluxanode** [comment]
It is working!  Thank you!

Now i just need to integrate it into my program!

Thanks again!

**Comment by Fluxanode** [comment]
Question - How did you determine the value for #define SPI_SPEED SD_SCK_MHZ(33)  // adjust to sd card ?

Also is there a way to change the name in windows explorer?  Currently it is Teensy with the sd name under it.  Or have it show up as a drive letter and an assigned name?

**Comment by WMXZ-EU** [comment]
The spi speed depends on your hardware 12 MHz should always work, but there is no rule. simply try it until it works.
To change the name of the portable device you have to modify the MTP code.
On drive letter, windows does not assign a drive letter to portable devices. 
If you wanted to change the disk name in the file explores, there is a sd_str string in the example that one can change
